### ISSUE TITLE
alexandria: Sporadic crash after scanning book (visible after issue #2)

### ISSUE THREAD

**Issue by abunghez** [abunghez/super-duo#5]
Process: it.jaschke.alexandria, PID: 15859
    java.lang.IllegalStateException: Fragment AddBook{2a18260f} not attached to Activity
            at android.support.v4.app.Fragment.getLoaderManager(Fragment.java:881)
            at it.jaschke.alexandria.AddBook.restartLoader(AddBook.java:149)
            at it.jaschke.alexandria.AddBook.access$300(AddBook.java:34)
            at it.jaschke.alexandria.AddBook$AddBookMessageReceiver.onReceive(AddBook.java:242)
            at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
            at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
            at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:155)
            at android.app.ActivityThread.main(ActivityThread.java:5696)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by abunghez** [comment]
Reverted the fix for issue #2 and thought of a more clever one.
